const assert = require("node:assert/strict")
const {readFileSync} = require("node:fs")
const {join} = require("node:path")
const {describe, it} = require("node:test")

const clientRoot = join(__dirname, "../src/client")

function source(path) {
    return readFileSync(join(clientRoot, path), "utf8")
}

describe("Rolling Skill native DSH Client", () => {
    it("adds exactly one finalized Assistant action without replacing conversation nodes", () => {
        const index = source("index.tsx")
        const action = source("conversation/CaseCaptureAction.tsx")
        const activeSession = source("conversation/active-session.ts")
        const dialog = source("conversation/CaseCaptureDialog.tsx")
        const combined = `${index}\n${action}\n${dialog}`

        assert.equal((index.match(/slots\.inject\("conversation\.chat\.assistant-actions"/gu) ?? []).length, 1)
        assert.match(index, /name:\s*"conversation\.chat\.assistant-actions"/u)
        assert.match(index, /id:\s*"rolling-skill-case-capture"/u)
        assert.match(action, /messageId/u)
        assert.match(action, /sessionId/u)
        assert.match(action, /registerActiveConversationSession/u)
        assert.match(activeSession, /lastObservedSessionId/u)
        assert.match(activeSession, /order\.at\(-1\)\s*\?\?\s*lastObservedSessionId/u)
        assert.match(dialog, /conversationCuration\.inspect/u)
        assert.match(dialog, /conversationCuration\.create/u)
        assert.match(dialog, /startSeq/u)
        assert.match(dialog, /datasetId/u)
        assert.match(dialog, /idempotencyKey/u)
        assert.doesNotMatch(combined, /conversation\.chat\.node/u)
        assert.doesNotMatch(dialog, /dangerouslySetInnerHTML/u)
        assert.doesNotMatch(dialog, /(?:episode|events|messages|snapshotPath|digest|runtimePath|providerId|installationId)\s*:/u)
    })

    it("projects durable Draft and saved ranges onto native flow keys", () => {
        const index = source("index.tsx")
        const controller = source("conversation/ConversationCurationMarkers.tsx")
        const projection = source("conversation/curation-markers.cjs")
        const css = source("workbench/workbench.css")

        assert.match(index, /slots\.inject\("conversation\.session\.header\.utilities"/u)
        assert.match(controller, /conversationCuration\.markers/u)
        assert.match(controller, /useSession/u)
        assert.match(controller, /data-chat-flow-key/u)
        assert.match(controller, /CSS\.escape/u)
        assert.match(controller, /rolling-skill:curation-markers-changed/u)
        assert.match(projection, /anchorSeq/u)
        assert.match(css, /rolling-skill-curation-draft/u)
        assert.match(css, /rolling-skill-curation-saved/u)
        assert.match(css, /data-rolling-skill-curation-status="draft"/u)
        assert.match(css, /data-rolling-skill-curation-status="saved"/u)
        assert.match(css, /border-inline-start/u)
        assert.match(controller, /markerDraftLegend/u)
        assert.match(controller, /markerSavedLegend/u)
        assert.doesNotMatch(`${index}\n${controller}`, /conversation\.chat\.node/u)
    })

    it("launches an independent workbench and keeps Settings administrative", () => {
        const index = source("index.tsx")
        const locale = source("locale.ts")
        const launcher = source("workbench/WorkbenchLauncher.tsx")
        const overlay = source("workbench/WorkbenchOverlay.tsx")
        const settings = source("settings/RollingSkillSettings.tsx")

        assert.match(index, /slots\.inject\("sidebar\.footer\.action"/u)
        assert.match(index, /name:\s*"sidebar\.footer\.action"/u)
        assert.match(index, /id:\s*"rolling-skill-workbench"/u)
        assert.match(index, /slots\.inject\("settings\.section"/u)
        assert.match(index, /name:\s*"settings\.section"/u)
        assert.match(index, /id:\s*"rolling-skill"/u)
        assert.match(index, /order:\s*20/u)
        assert.match(index, /label:\s*\(\)\s*=>\s*t\("nav"\)/u)
        assert.match(index, /locale\.register\(LOCALE_NAMESPACE,\s*DICTIONARIES\)/u)
        assert.match(locale, /export const zh/u)
        assert.match(locale, /export const en/u)
        assert.match(launcher, /rolling-skill:open-workbench/u)
        assert.match(overlay, /role="dialog"/u)
        assert.match(overlay, /aria-modal="true"/u)
        assert.match(overlay, /event\.key\s*===\s*"Escape"/u)
        assert.doesNotMatch(settings, /<ImportPanel/u)
        assert.match(settings, /settings\.selectRuntime/u)
        assert.match(settings, /curatorModelId/u)
        assert.match(settings, /rubricModelId/u)
        assert.match(settings, /judgeModelId/u)
        assert.doesNotMatch(settings, /<Workbench/u)
        assert.doesNotMatch(index, /conversation\.session["']/u)
        assert.doesNotMatch(index, /replaceChildren|createRoot/u)
    })

    it("groups workbench pages into four workflow sections", () => {
        const workbench = source("workbench/Workbench.tsx")
        const settings = source("settings/RollingSkillSettings.tsx")
        const locale = source("locale.ts")
        const css = source("workbench/workbench.css")

        assert.match(workbench, /const NAVIGATION_GROUPS/u)
        assert.match(workbench, /id:\s*"case-management"[\s\S]+label:\s*"caseManagement"/u)
        assert.match(workbench, /id:\s*"skill-installation"[\s\S]+label:\s*"skillAndInstallation"/u)
        assert.match(workbench, /id:\s*"evaluation-optimization"[\s\S]+label:\s*"evaluationAndOptimization"/u)
        assert.match(workbench, /rolling-skill-primary-tabs/u)
        assert.match(workbench, /rolling-skill-secondary-tabs/u)
        assert.match(workbench, /normalizeWorkbenchRoute/u)
        assert.match(locale, /caseManagement:\s*"Case 沉淀与管理"/u)
        assert.match(locale, /skillAndInstallation:\s*"Skill 与安装"/u)
        assert.match(locale, /evaluationAndOptimization:\s*"评测与优化"/u)
        assert.match(locale, /runtimeInstallation:\s*"Runtime 安装"/u)
        assert.match(css, /\.rolling-skill-primary-tabs/u)
        assert.match(css, /\.rolling-skill-secondary-tabs/u)
        assert.doesNotMatch(workbench, /ImportPanel|page:\s*"import"|page:\s*"diagnostics"/u)
        assert.doesNotMatch(settings, /ImportPanel|legacyImport|diagnostics/u)
    })

    it("uses the bounded same-origin API and aborts stale requests", () => {
        const api = source("api.ts")
        const workbench = source("workbench/Workbench.tsx")

        assert.match(api, /"\/rolling-skill\/api"/u)
        assert.match(api, /signal/u)
        assert.match(workbench, /new AbortController\(\)/u)
        assert.match(workbench, /controller\.abort\(\)/u)
        assert.doesNotMatch(`${api}\n${workbench}`, /electron|iframe|window\.open|target=["']_blank/iu)
    })

    it("uses Harness primitives and theme tokens without fixed page colors", () => {
        const workbench = source("workbench/Workbench.tsx")
        const css = source("workbench/workbench.css")

        assert.match(workbench, /@deepseek-ai\/dsh-client-ui-primitives/u)
        assert.match(workbench, /<Button/u)
        assert.match(css, /var\(--dsw-alias-bg-layer-2\)/u)
        assert.match(css, /var\(--dsw-alias-label-primary\)/u)
        assert.doesNotMatch(css, /#[0-9a-f]{3,8}\b|rgba?\(|hsla?\(/iu)
    })

    it("gives workbench actions visible semantics without stretching or text overflow", () => {
        const actionButton = source("workbench/ActionButton.tsx")
        const workbench = source("workbench/Workbench.tsx")
        const css = source("workbench/workbench.css")
        const panels = [
            "AutomaticCapturePanel.tsx",
            "CasesPanel.tsx",
            "CurationPanel.tsx",
            "CurationSessionView.tsx",
            "DatasetsPanel.tsx",
            "EvaluationsPanel.tsx",
            "InstallationsPanel.tsx",
            "OperatorPanel.tsx",
            "OptimizationPanel.tsx",
            "RawCasesPanel.tsx",
            "RubricPanel.tsx",
            "RubricSessionView.tsx",
            "RuntimeInteractions.tsx",
            "SkillsPanel.tsx",
        ].map((name) => source(`workbench/${name}`))

        assert.match(actionButton, /tone\s*=\s*"secondary"/u)
        assert.match(actionButton, /primary:\s*"primary"/u)
        assert.match(actionButton, /secondary:\s*"outline"/u)
        assert.match(actionButton, /quiet:\s*"ghost"/u)
        for (const panel of panels) {
            assert.match(panel, /ActionButton as Button/u)
            assert.doesNotMatch(panel, /import\s*\{[^}]*\bButton\b[^}]*\}\s*from\s*"@deepseek-ai\/dsh-client-ui-primitives"/u)
            assert.doesNotMatch(panel, /variant="(?:outline|ghost)"/u)
        }
        assert.match(workbench, /import\s*\{Button\}\s*from\s*"@deepseek-ai\/dsh-client-ui-primitives"/u)
        assert.match(workbench, /import\s*\{ActionButton\}\s*from\s*"\.\/ActionButton"/u)
        assert.match(workbench, /<ActionButton\s+size="sm"\s+onClick=\{reload\}/u)
        assert.match(css, /\.rolling-skill-action-button\s*\{[\s\S]*flex:\s*0 0 auto/u)
        assert.match(css, /\.rolling-skill-action-button\s*\{[\s\S]*white-space:\s*nowrap/u)
        assert.match(css, /text-overflow:\s*ellipsis/u)
        assert.match(css, /\.rolling-skill-actions\s*\{[\s\S]*flex-wrap:\s*wrap/u)
        assert.match(css, /@media \(max-width: 760px\)[\s\S]*align-items:\s*flex-start/u)
        assert.match(css, /@media \(max-width: 760px\)[\s\S]*box-sizing:\s*border-box/u)
        assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.rolling-skill-review-layout\s*\{[\s\S]*grid-template-columns:\s*1fr/u)
        assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.rolling-skill-header\s*\{[\s\S]*align-items:\s*flex-start/u)
    })

    it("ships native Dataset, Case, and Raw Case panels with refresh and recovery actions", () => {
        const datasets = source("workbench/DatasetsPanel.tsx")
        const cases = source("workbench/CasesPanel.tsx")
        const rawCases = source("workbench/RawCasesPanel.tsx")
        const markdown = source("workbench/MarkdownContent.tsx")
        const workbench = source("workbench/Workbench.tsx")

        assert.match(datasets, /datasets\.create/u)
        assert.match(datasets, /datasets\.bindSkill/u)
        assert.match(datasets, /datasets\.delete/u)
        assert.match(datasets, /datasets\.exportCsv/u)
        assert.match(cases, /cases\.refreshBatch/u)
        assert.match(cases, /cases\.delete/u)
        assert.match(cases, /cases\.get/u)
        assert.match(cases, /curation\.createCalibration/u)
        assert.match(cases, /caseScope/u)
        assert.match(cases, /pageSize/u)
        assert.match(cases, /<MarkdownContent/u)
        assert.match(markdown, /skipHtml/u)
        assert.match(markdown, /safeMarkdownLink/u)
        assert.doesNotMatch(markdown, /dangerouslySetInnerHTML|rehypeRaw|rehype-raw/u)
        assert.match(rawCases, /rawCases\.add/u)
        assert.match(rawCases, /rawCases\.createDraft/u)
        assert.match(rawCases, /rawCases\.evidence/u)
        assert.match(rawCases, /rawCases\.dispatch/u)
        assert.match(rawCases, /validateInNewSession/u)
        assert.match(rawCases, /rawCases\.update/u)
        assert.match(rawCases, /rawCases\.recycle/u)
        assert.match(rawCases, /repositoryId/u)
        assert.match(rawCases, /skillId/u)
        assert.match(rawCases, /search/u)
        assert.match(rawCases, /rawCaseSkillOptions/u)
        assert.match(rawCases, /rawCaseSkillGroups/u)
        assert.match(rawCases, /aria-label=\{t\("rawCaseSkillFilter"\)\}/u)
        assert.match(rawCases, /aria-pressed=\{skillScope === group\.key\}/u)
        assert.match(rawCases, /viewCaptureRange/u)
        assert.match(rawCases, /rawCaseEvidenceAdvanced/u)
        assert.match(rawCases, /captureEvidenceLoading/u)
        assert.match(rawCases, /rolling-skill-capture-evidence-timeline/u)
        assert.match(rawCases, /<details className="rolling-skill-capture-tool"/u)
        assert.match(rawCases, /setEvidenceAttempt/u)
        assert.match(rawCases, /rolling-skill:reveal-capture-range/u)
        assert.match(rawCases, /<details className="rolling-skill-advanced-evidence">[\s\S]+<pre>\{JSON\.stringify\(inspecting\.source/u)
        assert.doesNotMatch(rawCases, /<h4>\{t\("caseEvidence"\)\}<\/h4><pre>/u)
        assert.doesNotMatch(rawCases, /rangeOtherConversationHint/u)
        assert.doesNotMatch(source("locale.ts"), /请先在侧栏打开|Open the source conversation from the sidebar/u)
        assert.match(source("workbench/workbench.css"), /\.rolling-skill-capture-evidence-timeline/u)
        assert.match(source("workbench/workbench.css"), /\.rolling-skill-raw-group-filter/u)
        assert.match(source("workbench/workbench.css"), /\[role="dialog"\]:has\(> div > div > \.rolling-skill-capture-evidence\)[\s\S]+max-height:\s*calc\(100vh - 32px\)/u)
        assert.match(`${datasets}\n${cases}`, /recoverQuestions/u)
        assert.match(workbench, /<DatasetsPanel/u)
        assert.match(workbench, /<CasesPanel/u)
        assert.match(workbench, /<RawCasesPanel/u)
        assert.match(source("workbench/RubricPanel.tsx"), /rubrics\.migrateLegacy/u)
    })

    it("creates Datasets from stable managed Skill IDs without deployment evidence", () => {
        const datasets = source("workbench/DatasetsPanel.tsx")

        assert.match(datasets, /skills\.catalog/u)
        assert.match(datasets, /repositoryId:\s*selectedSkill\.repositoryId/u)
        assert.match(datasets, /skillId:\s*selectedSkill\.id/u)
        assert.match(datasets, /datasets\.bindSkill/u)
        assert.doesNotMatch(datasets, /datasets\.create[\s\S]{0,240}(?:path|runtimeId|providerId)\s*:/u)
        assert.doesNotMatch(datasets, /datasets\.bindSkill[\s\S]{0,360}(?:path|runtimeId|providerId)\s*:/u)
    })

    it("reuses a full-identity Runtime row for Case refresh and evaluations", () => {
        const runtime = source("workbench/RuntimeSelect.tsx")
        const evaluations = source("workbench/EvaluationsPanel.tsx")
        const cases = source("workbench/CasesPanel.tsx")
        const workbench = source("workbench/Workbench.tsx")

        assert.match(runtime, /displayName/u)
        assert.match(runtime, /version/u)
        assert.match(runtime, /executablePath/u)
        assert.match(evaluations, /runtimes\.list/u)
        assert.match(evaluations, /runtimes\.models/u)
        assert.match(evaluations, /evaluations\.start/u)
        assert.match(evaluations, /evaluations\.cancel/u)
        assert.match(evaluations, /evaluations\.delete/u)
        assert.match(evaluations, /activationMode/u)
        assert.match(evaluations, /caseScope/u)
        assert.match(evaluations, /computedScore/u)
        assert.match(evaluations, /<RuntimeSelect/u)
        assert.doesNotMatch(evaluations, /useState\("high"\)/u)
        assert.match(evaluations, /effort:\s*effort\s*\|\|\s*null/u)
        assert.match(evaluations, /effort:\s*judgeEffort\s*\|\|\s*null/u)
        assert.match(cases, /<RuntimeSelect/u)
        assert.match(workbench, /<EvaluationsPanel/u)
    })

    it("requires a Released managed version and checks its target installation", () => {
        const evaluations = source("workbench/EvaluationsPanel.tsx")

        assert.match(evaluations, /skills\.versions/u)
        assert.match(evaluations, /installations\.list/u)
        assert.match(evaluations, /version\.state\s*===\s*"released"/u)
        assert.match(evaluations, /versionId,/u)
        assert.match(evaluations, /selectedInstallation/u)
        assert.doesNotMatch(evaluations, /evaluations\.start[\s\S]{0,400}(?:path|commit|contentDigest)\s*:/u)
    })

    it("exposes managed Skill release and Runtime installation as separate native flows", () => {
        const skills = source("workbench/SkillsPanel.tsx")
        const installations = source("workbench/InstallationsPanel.tsx")
        const workbench = source("workbench/Workbench.tsx")

        assert.match(skills, /skills\.catalog/u)
        assert.match(skills, /skills\.createCandidate/u)
        assert.match(skills, /skills\.release/u)
        assert.match(skills, /skills\.deprecate/u)
        assert.match(skills, /installations\.start/u)
        assert.match(skills, /installations\.cancel/u)
        assert.doesNotMatch(skills, /installations\.inspect/u)
        assert.match(skills, /installations\.get/u)
        assert.match(skills, /installations\.send/u)
        assert.match(skills, /RuntimeInteractions/u)
        assert.match(skills, /targets:\s*runtimeIds\.map\(\(selectedRuntimeId\)\s*=>\s*\(\{runtimeId:\s*selectedRuntimeId,\s*modelId:\s*null,\s*effort:\s*null,/u)
        assert.doesNotMatch(skills, /targets:[^\n]+effort:\s*"high"/u)
        assert.match(workbench, /<SkillsPanel/u)
        assert.match(workbench, /<InstallationsPanel/u)
        assert.match(installations, /installations\.list/u)
        assert.match(installations, /installations\.get/u)
        assert.doesNotMatch(installations, /installations\.inspect/u)
        assert.match(installations, /installationAudit/u)
        assert.match(installations, /trustedJobId/u)
        assert.match(installations, /expectedDigest/u)
        assert.match(installations, /RuntimeInteractions/u)
    })

    it("opens native source pickers for local Skill imports", () => {
        const skills = source("workbench/SkillsPanel.tsx")
        const locale = source("locale.ts")

        assert.match(skills, /skills\.chooseSource/u)
        assert.match(skills, /sourceKind === "git-url"/u)
        assert.match(skills, /chooseSkillFolder/u)
        assert.match(skills, /chooseSkillZip/u)
        assert.match(skills, /selectedSkillSource/u)
        assert.match(locale, /chooseSkillFolder:\s*"选择文件夹"/u)
        assert.match(locale, /chooseSkillZip:\s*"选择 ZIP 文件"/u)
        assert.match(skills, /sourceLocation\s*\?\s*<div className="rolling-skill-selected-source"/u)
        assert.match(locale, /revealRepository:\s*"打开受管 Skill 文件夹"/u)
        assert.doesNotMatch(skills, /placeholder=\{t\("skillSourceLocation"\)\}/u)
    })

    it("separates Skill import, version management, and installation without losing the selected Skill", () => {
        const skills = source("workbench/SkillsPanel.tsx")
        const locale = source("locale.ts")

        assert.match(skills, /type SkillManagementTab = "import" \| "versions" \| "install"/u)
        assert.match(skills, /aria-label=\{t\("skillManagementSections"\)\}/u)
        assert.match(skills, /skillTab === "import"/u)
        assert.match(skills, /skillTab === "versions"/u)
        assert.match(skills, /skillTab === "install"/u)
        assert.match(skills, /value=\{detail\?\.skill\.id \?\? ""\}/u)
        assert.match(skills, /detail\?\.skill\.id \?\? initialSkillId/u)
        assert.doesNotMatch(skills, /if \(!detail && requestedSkill\)/u)
        assert.match(locale, /skillImportTab:\s*"导入"/u)
        assert.match(locale, /skillVersionsTab:\s*"版本管理"/u)
        assert.match(locale, /skillInstallTab:\s*"安装"/u)
        assert.match(locale, /currentManagedSkill:\s*"当前 Skill"/u)
    })

    it("renders structured Judge, score, and Case-scoped Trace evidence", () => {
        const evaluations = source("workbench/EvaluationsPanel.tsx")

        assert.match(evaluations, /EvaluationRunEvidence/u)
        assert.match(evaluations, /EvaluationScoreBreakdown/u)
        assert.match(evaluations, /EvaluationTrace/u)
        assert.match(evaluations, /criterionScores/u)
        assert.match(evaluations, /assessments/u)
        assert.match(evaluations, /traceEvidence\.entries/u)
        assert.match(evaluations, /traceScopeCase/u)
        assert.doesNotMatch(evaluations, /JSON\.stringify\(\{computedScore/u)
    })

    it("ships native Operator and Optimization panels without private control fields", () => {
        const operator = source("workbench/OperatorPanel.tsx")
        const optimization = source("workbench/OptimizationPanel.tsx")
        const interactions = source("workbench/RuntimeInteractions.tsx")
        const workbench = source("workbench/Workbench.tsx")

        assert.match(operator, /operators\.start/u)
        assert.match(operator, /operators\.pause/u)
        assert.match(operator, /operators\.resume/u)
        assert.match(operator, /operators\.approve/u)
        assert.match(operator, /operators\.artifacts/u)
        assert.match(operator, /operators\.send/u)
        assert.match(operator, /RuntimeInteractions/u)
        assert.match(operator, /<RuntimeSelect/u)
        assert.match(optimization, /optimizations\.start/u)
        assert.match(optimization, /optimizations\.pause/u)
        assert.match(optimization, /optimizations\.resume/u)
        assert.match(optimization, /optimizations\.cancel/u)
        assert.match(optimization, /optimizations\.report/u)
        assert.match(optimization, /optimizationTimeline/u)
        assert.match(interactions, /interactions\.list/u)
        assert.match(interactions, /interactions\.resolve/u)
        assert.match(workbench, /<OperatorPanel/u)
        assert.match(workbench, /<OptimizationPanel/u)
        assert.doesNotMatch(operator, /useState\("high"\)/u)
        assert.match(operator, /effort:\s*effort\s*\|\|\s*null/u)
        assert.doesNotMatch(optimization, /effort:\s*"high"/u)
        assert.doesNotMatch(`${operator}\n${optimization}`, /capabilityId|socketPath|childEnvironment|executablePath\s*:/u)
    })

    it("ships the complete automatic capture settings and status panel", () => {
        const automatic = source("workbench/AutomaticCapturePanel.tsx")
        const modelEffort = source("workbench/ModelEffortSelect.tsx")
        const operator = source("workbench/OperatorPanel.tsx")
        const evaluations = source("workbench/EvaluationsPanel.tsx")
        const workbench = source("workbench/Workbench.tsx")

        assert.match(automatic, /automatic\.status/u)
        assert.match(automatic, /automatic\.update/u)
        assert.match(automatic, /automatic\.runOnce/u)
        assert.match(automatic, /scheduler\.enable/u)
        assert.match(automatic, /scheduler\.disable/u)
        assert.match(automatic, /scheduled/u)
        assert.match(automatic, /automatic/u)
        assert.match(automatic, /while-harness-running/u)
        assert.match(automatic, /always/u)
        assert.match(automatic, /weekly/u)
        assert.match(automatic, /<RuntimeSelect/u)
        assert.doesNotMatch(automatic, /useState\("low"\)/u)
        assert.match(automatic, /effort:\s*effort\s*\|\|\s*null/u)
        assert.match(modelEffort, /reasoningEfforts/u)
        assert.match(modelEffort, /runtimeDefaultLabel/u)
        assert.match(automatic, /<ModelEffortSelect/u)
        assert.match(operator, /<ModelEffortSelect/u)
        assert.equal((evaluations.match(/<ModelEffortSelect/gu) ?? []).length, 2)
        assert.doesNotMatch(`${automatic}\n${operator}\n${evaluations}`, /\["low",\s*"medium",\s*"high"/u)
        assert.match(workbench, /<AutomaticCapturePanel/u)
    })

    it("uses explicit hour and minute selectors for automatic capture time", () => {
        const automatic = source("workbench/AutomaticCapturePanel.tsx")
        const css = source("workbench/workbench.css")

        assert.doesNotMatch(automatic, /type="time"/u)
        assert.match(automatic, /const HOURS = Array\.from\(\{length:\s*24\}/u)
        assert.match(automatic, /const MINUTES = Array\.from\(\{length:\s*60\}/u)
        assert.match(automatic, /aria-label=\{t\("captureHour"\)\}/u)
        assert.match(automatic, /aria-label=\{t\("captureMinute"\)\}/u)
        assert.match(css, /\.rolling-skill-time-selects/u)
    })

    it("explains automatic model roles and background scheduling in user language", () => {
        const automatic = source("workbench/AutomaticCapturePanel.tsx")
        const locale = source("locale.ts")
        const css = source("workbench/workbench.css")

        assert.match(automatic, /settings\.get/u)
        assert.match(automatic, /rolling-skill-automatic-flow-summary/u)
        assert.match(automatic, /automaticFlowSummaryPrefix/u)
        assert.match(automatic, /automaticFlowSummarySuffix/u)
        assert.doesNotMatch(automatic, /rolling-skill-step|<article>/u)
        assert.match(automatic, /schedulerExplanation/u)
        assert.match(locale, /automaticFlowSummaryPrefix:\s*"检测模型识别完整 Case 并判断归属；完全自动模式由 Curator（"/u)
        assert.match(locale, /automaticFlowSummarySuffix:\s*"）整理，校验通过后保存为 Case，不运行 Judge。"/u)
        assert.match(locale, /enableScheduler:\s*"启用后台定时运行"/u)
        assert.match(locale, /disableScheduler:\s*"停止关闭后定时运行"/u)
        assert.match(locale, /schedulerExplanation:\s*"需要在当前用户下创建系统定时任务[^"\n]*不会安装新软件。"/u)
        assert.match(css, /\.rolling-skill-automatic-flow-summary/u)
        assert.doesNotMatch(css, /\.rolling-skill-automatic-flow article|\.rolling-skill-step/u)
    })

    it("makes automatic capture routing and scheduler actions explicit", () => {
        const automatic = source("workbench/AutomaticCapturePanel.tsx")
        const modelEffort = source("workbench/ModelEffortSelect.tsx")
        const locale = source("locale.ts")
        const css = source("workbench/workbench.css")

        assert.match(automatic, /skills\.catalog/u)
        assert.match(automatic, /candidateTargets/u)
        assert.match(automatic, /candidateDatasetOptions/u)
        assert.match(automatic, /disabled=\{selectableDatasets\.length\s*===\s*0\s*&&\s*!target\}/u)
        assert.match(automatic, /disabled=\{option\.disabled\}/u)
        assert.match(automatic, /candidateDatasetOnlyOne/u)
        assert.match(automatic, /targets:\s*candidateTargets/u)
        assert.match(automatic, /await updateAutomaticSettings\(\)[\s\S]{0,180}scheduler\.enable/u)
        assert.doesNotMatch(automatic, /status\?\.executionLocation\s*!==\s*"always"/u)
        assert.match(modelEffort, /supportedReasoningEfforts/u)
        assert.match(automatic, /modelCatalogRevision/u)
        assert.match(automatic, /setModels\(\[\]\)[\s\S]{0,120}setModelId\(""\)/u)
        assert.match(automatic, /candidateSkillRows/u)
        assert.match(automatic, /skill\.status\s*!==\s*"valid"/u)
        assert.match(locale, /automaticRuntime:\s*"Case 检测 Runtime"/u)
        assert.match(locale, /automaticDetectionModel:\s*"Case 检测模型"/u)
        assert.match(locale, /candidateSkills:\s*"候选 Skill 与数据集"/u)
        assert.match(locale, /enableScheduler:\s*"启用后台定时运行"/u)
        assert.match(automatic, /rolling-skill-form-actions/u)
        assert.match(css, /\.rolling-skill-form-actions[\s\S]{0,240}justify-content:\s*space-between/u)
        assert.match(css, /\.rolling-skill-candidate-target-list[\s\S]{0,220}max-height:[^;]+;[\s\S]{0,120}overflow-y:\s*auto/u)
    })

    it("keeps copy-only legacy migration code hidden from released UI", () => {
        const panel = source("workbench/ImportPanel.tsx")
        const workbench = source("workbench/Workbench.tsx")
        const settings = source("settings/RollingSkillSettings.tsx")

        assert.match(panel, /legacyImport\.status/u)
        assert.match(panel, /legacyImport\.run/u)
        assert.match(panel, /confirmImport/u)
        assert.doesNotMatch(workbench, /<ImportPanel/u)
        assert.doesNotMatch(settings, /<ImportPanel/u)
    })
})
